admins:
- jsmith
cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: siddharthachaki02@gmail.com
      name: John Smith
      password: $2b$12$RClEpQ7A4PTrbaLzTSzqjOn7zzfd5tISVUZkjG9A.Uj83Ok4R4U/G
    rbriggs:
      email: siddharthachaki02@gmail.com
      name: Rebecca Briggs
      password: $2b$12$k50p7GnX8LiN5/wUgFppo.yAqF2HpGVSHkHuWCsddUVbLfRtXdSM6
preauthorized:
  emails:
  - siddharthachaki02@gmail.com
