admins:
- jsmith
cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: siddharthachaki02@gmail.com
      name: John Smith
      password: $2b$12$6gSK0AEajt7Z8UZQaDKC3u4c8n0Rm7BU9VM34btyASNIGlnPiZD62
    rbriggs:
      email: siddharthachaki02@gmail.com
      name: Rebecca Briggs
      password: $2b$12$PWqGorJ2qKYe1Eb3M6LT2uhaOMMMC85Tji7SXo/AiYpjfc7Bzt0va
preauthorized:
  emails:
  - siddharthachaki02@gmail.com
